# Generated by Django 3.2.23 on 2024-01-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('fullname', models.TextField()),
                ('author', models.TextField()),
                ('abstract', models.TextField()),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('publish', models.DateTimeField()),
                ('journal', models.CharField(max_length=250)),
                ('issn', models.CharField(max_length=9)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='Published', max_length=10)),
            ],
            options={
                'ordering': ('publish',),
            },
        ),
    ]
